# Generated by Django 2.0.6 on 2018-07-14 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country_code_3ch', models.CharField(max_length=3)),
                ('state_code', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=20)),
                ('city_name', models.CharField(max_length=50)),
                ('lat', models.FloatField(blank=True, default=None, null=True)),
                ('long', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont_name', models.CharField(max_length=100)),
                ('cont_email', models.EmailField(max_length=150)),
                ('cont_subj', models.CharField(max_length=150)),
                ('cont_msg', models.TextField(max_length=250)),
                ('cont_src', models.CharField(max_length=20)),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Contact Date')),
            ],
        ),
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_cat', models.CharField(max_length=60)),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Content Category added')),
            ],
        ),
        migrations.CreateModel(
            name='ContentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont_link', models.CharField(blank=True, max_length=250, null=True)),
                ('cont_desc', models.TextField(blank=True, null=True)),
                ('cont_heading', models.TextField(blank=True, null=True)),
                ('cont_image', models.CharField(blank=True, max_length=250, null=True)),
                ('img_flag', models.BooleanField(default=False)),
                ('scrap_flag', models.BooleanField(default=False)),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Content link was added')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=50)),
                ('country_code_2ch', models.CharField(max_length=2)),
                ('country_code_3ch', models.CharField(max_length=3)),
                ('isd_code', models.CharField(blank=True, max_length=20, null=True)),
                ('national_language_code', models.CharField(blank=True, max_length=100, null=True)),
                ('national_language_desc', models.CharField(blank=True, max_length=15, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=6, null=True)),
                ('currency_desc', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semail', models.EmailField(blank=True, max_length=254)),
                ('subscribe_key', models.CharField(blank=True, max_length=200)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('otp', models.CharField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_id', models.CharField(max_length=50, unique=True)),
                ('pet_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=1)),
                ('age', models.CharField(blank=True, max_length=5, null=True)),
                ('weight', models.CharField(blank=True, max_length=5, null=True)),
                ('special_inst', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='profile_images')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Pet added')),
            ],
        ),
        migrations.CreateModel(
            name='Pet_Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_breed', models.CharField(max_length=50)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('origin', models.CharField(blank=True, max_length=50, null=True)),
                ('body_type', models.CharField(blank=True, max_length=50, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Pet Breed added')),
            ],
        ),
        migrations.CreateModel(
            name='Pet_Owner_Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Interest_Desc', models.CharField(max_length=60)),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Pet Owner Interest added')),
            ],
        ),
        migrations.CreateModel(
            name='Pet_Owner_Interest_Ref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Pet added')),
                ('interest_id', models.ManyToManyField(blank=True, to='pets.Pet_Owner_Interest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pet_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(max_length=30)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Petjibeuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm_key', models.CharField(blank=True, max_length=200)),
                ('first_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('addr1', models.TextField(blank=True, null=True)),
                ('addr2', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=5, null=True)),
                ('state', models.CharField(blank=True, max_length=5, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('otherEmail', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('ownpet', models.BooleanField(default=False)),
                ('if_member', models.IntegerField(default=0)),
                ('interest_ids', models.TextField(blank=True)),
                ('otherstate', models.CharField(blank=True, max_length=50, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('lat', models.FloatField(default=0.0)),
                ('long', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_Date', models.DateTimeField(auto_now_add=True, verbose_name='Search Date')),
                ('zip_code', models.CharField(max_length=15)),
                ('radius', models.CharField(max_length=15)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Pet_Owner_Interest')),
                ('pet_breed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Pet_Breed')),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Pet_Type')),
            ],
        ),
        migrations.CreateModel(
            name='SearchResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_parent_nick_name', models.CharField(blank=True, max_length=30, null=True)),
                ('dist_from_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('pet_count', models.CharField(blank=True, max_length=5, null=True)),
                ('interest', models.CharField(blank=True, max_length=50, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Pet added')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country_code_3ch', models.CharField(max_length=3)),
                ('state_name', models.CharField(max_length=50)),
                ('state_code', models.CharField(max_length=20)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Pet added')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_email', models.EmailField(max_length=150)),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Subscriber added')),
            ],
        ),
        migrations.CreateModel(
            name='UserPasswordKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('valid_till', models.DateTimeField(default=pets.models.get_default_my_date)),
                ('spent', models.BooleanField(default=False)),
                ('mail_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pet_breed',
            name='pet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Pet_Type'),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.Pet_Breed'),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Pet_Type'),
        ),
        migrations.AddField(
            model_name='pet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentdetails',
            name='cont_stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Status'),
        ),
        migrations.AddField(
            model_name='contentdetails',
            name='content_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.ContentCategory'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.State'),
        ),
    ]
