# Generated by Django 2.0.6 on 2018-07-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresults',
            name='search_inst',
            field=models.ManyToManyField(blank=True, null=True, to='pets.Search'),
        ),
    ]
