# Generated by Django 2.0.6 on 2018-08-18 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0003_auto_20180721_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsConn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownername', models.CharField(blank=True, max_length=100, null=True)),
                ('connected', models.TextField(blank=True, null=True)),
                ('invited', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
