# Generated by Django 2.0.6 on 2018-08-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_friendsconn'),
    ]

    operations = [
        migrations.AddField(
            model_name='petjibeuser',
            name='profile_pic',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
